-- https://www.ma.imperial.ac.uk/~buzzard/xena/natural_number_game/?world=3&level=6

induction b with d hd,
rw add_zero,
rw mul_zero,
rw mul_zero,
refl,
rw mul_succ,
rw mul_succ,
rw add_succ,
rw add_succ,
rw hd,
rw add_assoc,
rw add_comm d a,
rw add_assoc,
refl,